Repository stolostron/must-gather, pull requests merged in 2022-04, with the labels that each got.

#91 collect output for ramen resources
  collection-scripts/gather
Labels: dco-signoff: yes, ok-to-test

#93 Update pull_request_template.md
  .github/pull_request_template.md
Labels: lgtm, approved, dco-signoff: yes, do-not-merge/hold

#94 managedcluster details are empty
  collection-scripts/gather
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#97 MGMT-9387: Inspect assisted-installer CRs in all namespaces
  collection-scripts/gather
Labels: lgtm, approved, dco-signoff: yes, needs-ok-to-test

#98 Gather info about VolSync CRs on spoke clusters
  collection-scripts/gather
Labels: lgtm, approved, dco-signoff: yes

#99 Update owners
  OWNERS
Labels: lgtm, approved, dco-signoff: yes, do-not-merge/hold

#100 update cli version
  Dockerfile
Labels: lgtm, approved, dco-signoff: yes

#101 remove docker file prow
  Dockerfile.prow
Labels: lgtm, approved
