Repository stolostron/must-gather, pull requests merged in 2024-08, with the labels that each got.

#239 Move `Dockerfile.rhtap` to `build/`
  .tekton/must-gather-acm-212-pull-request.yaml
  .tekton/must-gather-acm-212-push.yaml
  Dockerfile
  Makefile
  build/Dockerfile
  build/Dockerfile.rhtap
Labels: lgtm, approved, dco-signoff: yes

#240 Adjust MintMaker update schedule
  .github/renovate.json
Labels: lgtm, approved, dco-signoff: yes

#244 Use `baseBranches` RegEx to override MintMaker
  .github/renovate.json
Labels: lgtm, approved, dco-signoff: yes

#245 [release-2.11] Use array for Renovate schedule
  .github/renovate.json
Labels: lgtm, approved, dco-signoff: yes

#247 Change MintMaker RegEx to allowlist
  .github/renovate.json
Labels: lgtm, approved, dco-signoff: yes

#253 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/must-gather-acm-210-pull-request.yaml
  .tekton/must-gather-acm-210-push.yaml
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#261 ACM-13458: Add imageclusterinstall to MCE gather
  collection-scripts/gather_mce_logs
Labels: lgtm, approved, dco-signoff: yes

#251 Remove `baseBranches`
  .github/renovate.json
Labels: lgtm, approved, dco-signoff: yes, stale

#266 [ACM-13625] Added internal Installer CRDs to must-gather
  collection-scripts/gather_hub_logs
  collection-scripts/gather_mce_logs
Labels: lgtm, approved, dco-signoff: yes

#273 ACM-13623: Add clusterinstance to ACM gather
  collection-scripts/gather_hub_logs
Labels: lgtm, approved, dco-signoff: yes
